print(" my daily routine")
print("" \
"")
print("     wake up")
print(" brush my teeth")
print("  go to school")
print(" come back home")
print("     bath")
print("do 1 hour of homwork")
print("   eat lunch")
print(" go play outside")
print(" watch 30 min tv")
print("   eat dinner")
print("     sleep")
print(1*7,"hours of study a week")
#my project
